// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqeatzeiiynvdzfexyuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxZWF0emVpaXludmR6ZmV4eXV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MDAxNTMsImV4cCI6MjA2MDI3NjE1M30.auEPZdq0iRySXCqvVY2xxXyqdV4OkZHcEIW1pkySH_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);